apiVersion: v1
kind: Service
metadata:
  name: {{ include "student-api.fullname" .}}
  labels:
    app.kubernetes.io/name: student-api
    app.kubernetes.io/instance: student-api
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "student-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}