services:
  db:
    image: postgres:17
    container_name: student-api-postgres
    environment:
      POSTGRES_USER: student_api
      POSTGRES_PASSWORD: pa55word
      POSTGRES_DB: student_api
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U student_api"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  api:
    build:
      context: .
      target: debug-run
    container_name: student-api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "4000:4000"
    command: ["./students_api"]


volumes:
  pgdata: