services:
  db:
    image: postgres:17
    container_name: student-api-db
    environment:
      POSTGRES_USER: student_api
      POSTGRES_PASSWORD: pa55word
      POSTGRES_DB: student_api
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U student_api"]
      interval: 5s
      timeout: 5s
      retries: 5

  api1:
    image: ghcr.io/sai29/one2n_sre_bootcamp:v0.1.0
    container_name: student-api-1
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      STUDENT_API_DB_DSN: postgres://student_api:pa55word@db:5432/student_api?sslmode=disable
    expose:
      - "4000"

  api2:
    image: ghcr.io/sai29/one2n_sre_bootcamp:v0.1.0
    container_name: student-api-2
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      STUDENT_API_DB_DSN: postgres://student_api:pa55word@db:5432/student_api?sslmode=disable
    expose:
      - "4000"

  nginx:
    image: nginx:alpine
    container_name: student-api-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2

volumes:
  pgdata:
