apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: student-api
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: student-api
      app.kubernetes.io/instance: student-api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s