apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.db.externalSecretName }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.db.targetSecretName }}
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: {{ .Values.db.vaultPath }}
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.db.vaultPath }}
        property: password

    - secretKey: username
      remoteRef:
        key: {{ .Values.db.vaultPath }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.db.vaultPath }}
        property: password
      