apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: student-api-db-observability
  namespace: observability
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: postgres-exporter-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: {{ .Values.db.vaultPath }}
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.db.vaultPath }}
        property: password
