apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  namespace: observability
spec:
  provider:
    vault:
      server: {{ .Values.vault.address }}
      path: {{ .Values.vault.kvPath }}
      version: v2
      auth:
        tokenSecretRef:
          name: {{ .Values.vault.tokenSecretName }}
          key: token
