server:
  dataStorage:
    enabled: false

  securityContext:
    runAsUser: 100
    runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true

  ha:
    enabled: false

  extraEnvironmentVars:
    SKIP_SETCAP: "true"

ui:
  enabled: true
