apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: student-api-db
  namespace: student-api
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: student-api-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: student-api/db
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: student-api/db
        property: password
