apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-api-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  source:
    repoURL: https://github.com/sai29/one2n_sre_bootcamp.git
    targetRevision: main
    path: helm/secrets

  destination:
    server: https://kubernetes.default.svc
    namespace: student-api
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true