# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: student-api
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: "2"

# spec:
#   project: default

#   source:
#     repoURL: https://github.com/sai29/one2n_sre_bootcamp.git
#     targetRevision: main
#     path: helm/student-api
#     helm:
#       valueFiles:
#         - helm/environments/local/student-api.yml

#   destination:
#     server: https://kubernetes.default.svc
#     namespace: student-api

#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
