apiVersion: v1
kind: ConfigMap
metadata:
  name: student-api-config
  namespace: student-api
data:
  SERVER_PORT: "4000"
  GIN_MODE: "release"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
  namespace: student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
    spec:
      nodeSelector:
        type: application

      initContainers:
        - name: run-migrations
          image: localhost:5000/student-api-migrations:v0.1.1
          command:
            - sh
            - -c
            - |
              migrate -path=/migrations \
                -database "postgres://${DB_USERNAME}:${DB_PASSWORD}@student-api-db:5432/student_api?sslmode=disable" \
                up
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: student-api-db-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: student-api-db-secret
                  key: DB_PASSWORD


      containers:
        - name: student-api
          image: localhost:5000/student-api:v0.1.1
          ports:
            - containerPort: 4000
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: student-api-config
                  key: SERVER_PORT
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: student-api-db-secret
                  key: DATABASE_URL
            - name: GIN_MODE
              valueFrom:
                configMapKeyRef:
                  name: student-api-config
                  key: GIN_MODE
            - name: DB_HOST
              value: student-api-db
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: student_api
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: student-api-db-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: student-api-db-secret
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: student-api
  namespace: student-api
spec:
  type: NodePort
  selector:
    app: student-api
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30080