apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: argocd-probe
  namespace: observability
  labels:
    release: kube-prometheus-stack
spec:
  jobName: argocd-server
  interval: 30s
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.observability.svc.cluster.local:9115
    path: /probe
  targets:
    staticConfig:
      static:
        - https://argocd-server.argocd.svc.cluster.local
      labels:
        service: argocd
        endpoint: server
  module: http_2xx_insecure