apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: student-api-probe
  namespace: observability
  labels:
    release: kube-prometheus-stack
spec:
  jobName: student-api-healthcheck
  interval: 30s
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
    path: /probe
  targets:
    staticConfig:
      static:
        - http://student-api.student-api.svc.cluster.local:4000/v1/healthcheck
      labels:
        service: student-api
        endpoint: healthcheck
  module: http_2xx