config:
  datasource:
    host: student-api-db.student-api.svc.cluster.local
    port: "5432"
    database: student_api
    user: $(DB_USERNAME)
    password: $(DB_PASSWORD)
    sslmode: disable

extraEnvs:
  - name: DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: student-api-db-secret
        namespace: student-api
        key: DB_USERNAME
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: student-api-db-secret
        namespace: student-api
        key: DB_PASSWORD

serviceMonitor:
  enabled: true
  namespace: observability
  labels:
    release: kube-prometheus-stack

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

nodeSelector:
  type: dependent_services