apiVersion: batch/v1
kind: Job
metadata:
  name: student-api-migrations
  labels:
    app: student-api-migrations
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        app: student-api-migrations
    spec:
      restartPolicy: Never
      containers:
        - name: student-api-migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - migrate
            - -path=/migrations
            - -database=$(DATABASE_URL)
            - up
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecretName }}
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecretName }}
                  key: DB_PASSWORD
            - name: DB_HOST
              value: student-api-db
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: student_api
            - name: DATABASE_URL
              value: postgres://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=disable
