apiVersion: batch/v1
kind: Job
metadata:
  name: student-api-migrations
  labels:
    app: student-api-migrations
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        app: student-api-migrations
    spec:
      restartPolicy: Never
      containers:
        - name: student-api-migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.envSecretName }}