fullnameOverride: student-api-db

auth:
  existingSecret: student-api-db-secret
  secretKeys:
    adminPasswordKey: POSTGRES_PASSWORD


primary:
  persistence:
    enabled: true
    size: 1Gi

volumePermissions:
  enabled: true

podSecurityContext:
  fsGroup: 1001

containerSecurityContext:
  runAsUser: 1001
