apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 1.2.1
    helm:
      values: |
        installCRDs: false
        crds:
          createPushSecret: false
          createClusterPushSecret: false
        processPushSecret: false
        processClusterPushSecret: false
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  # MUST BE AT THE SPEC LEVEL, OUTSIDE SOURCE
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/args

  # THIS FORCES THE ARGUMENTS
  patches:
    - target:
        kind: Deployment
        name: external-secrets-operator
      patch: |
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --enable-push-secret-reconciler=false
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --enable-cluster-push-secret-reconciler=false

  syncPolicy:
    automated:
      prune: true
      selfHeal: true